### ISSUE TITLE
/admin/login not working

### ISSUE THREAD

**Issue by Sebubu** [Theodo-UK/nestjs-admin#144]
Hey guys

I like to create a basic nestjs template with typeorm, jwt, graphql and I also want to add nestjs-admin.
Unfortunately, it doesn't work.
## Problem
After going through the nestjs-admin installation instructions, `/admin/login` is not exposed and I have no idea why. I receive a 404 when requesting the admin login.

## Steps to reproduce the problem

1. Clone https://gitlab.com/sebubu/nestjs-backend-template/tree/nest-admin
2. `npm install`
3. Edit database credentials in `.env`
4. Run migrations with `npm run typeorm:migration:run`
5. Create admin `npx nestjs-admin createAdminUser`
6. Run nest `npm run start:dev`
7. Go to http://localhost:3000/admin/login

## Hints
According to the nestjs output, the `DefaultAdminModule` is not initialized although it is present in the [AppModule imports](https://gitlab.com/sebubu/nestjs-backend-template/blob/nest-admin/src/app.module.ts).

<img width="752" alt="Screenshot 2019-12-15 at 14 37 23" src="https://user-images.githubusercontent.com/8782386/70859067-848a8b80-1f48-11ea-91db-7029b54c03fe.png">

Database tables are correctly created although I don't get why nestjs-admin creates tables like `dummyentities`.

<img width="270" alt="Screenshot 2019-12-15 at 14 34 39" src="https://user-images.githubusercontent.com/8782386/70859055-43927700-1f48-11ea-9593-5594972a2136.png">

Best regards

Sevi

**Comment by therealedsheenan** [comment]
@Sebubu You didn't include the `DefaultAdminModule` and `DefaultAdminSite` in your user module here: https://gitlab.com/sebubu/nestjs-backend-template/blob/nest-admin/src/auth/users/users.module.ts

**Comment by Sebubu** [comment]
> @Sebubu You didn't include the `DefaultAdminModule` and `DefaultAdminSite` in your user module here: https://gitlab.com/sebubu/nestjs-backend-template/blob/nest-admin/src/auth/users/users.module.ts

`DefaultAdminSite` helped. The project seems to have a lot of bugs though.

Is this project dead?

**Comment by TheBigBadBunce** [comment]
@Sebubu - To answer your question, not dead but under-loved right now as most of us don't have enough time to work on it 😞 Hopefully this will improve in the near future - in the meantime please keep opening issues as you encounter them and we'll fix/document as many as we're able. Cheers!

**Comment by williamdclt** [comment]
**About the project being dead:**
No, but as Sam says it's under-loved. I am maintaining it on my downtime which is scarce these days sadly! I am currently doing a pass over the main problems encountered by people

**"I don't get why nestjs-admin creates tables like dummyentities"**
Definitely a bug (bad TS config), should now be fixed in `0.4.0`.

**About /admin/login not being exposed**
I believe @therealedsheenan pointed you in the right direction. Did it all work out? I'd love some feedback on how clear this whole `DefaultAdminModule` and `DefaultAdminSite` thing is!

I'll close this as I think it's resolved, let's reopen it if needed
